### ISSUE TITLE
Inconsistent documentation regarding filenames ending in Z

### ISSUE THREAD

**Issue by kwilcox** [ioos/ioosngdac#111]
Should data files that are uploaded to the DAC FTP site end in `Z`? There is conflicting documentation in the [File Naming Conventions](https://github.com/ioos/ioosngdac/wiki/NGDAC-NetCDF-File-Format-Version-2#file-naming-conventions) section.

I'm leaning towards yes... please confirm!

**Comment by lukecampbell** [comment]
It looks like no Z suffix to the folder name. Data files can be pretty much anything, the aggregation looks for netCDF files. I haven't tested what happens if the files are out of order, but I remember hearing that ERDDAP aggregates them just fine, even if the filenames are not in any specific order.

**Comment by lukecampbell** [comment]
Example upload:

```
./rutgers/silbo-20160413T1534/silbo_20160916T0422Z_rt.nc
./rutgers/silbo-20160413T1534/silbo_20160915T1620Z_rt.nc
./rutgers/clark-20160624T1800/clark_20160915T0114Z_rt.nc
./rutgers/clark-20160624T1800/clark_20160916T1215Z_rt.nc
./rutgers/clark-20160624T1800/clark_20160915T1700Z_rt.nc
./rutgers/clark-20160624T1800/clark_20160915T2040Z_rt.nc
```
