### ISSUE TITLE
DAC ERDDAP and QC outstanding issue

### ISSUE THREAD

**Issue by kerfoot** [ioos/ioosngdac#127]
A dataset with no QC information was submitted last week.  My understanding was any dataset that was missing QC (variable:ancillary_variables) would be QC'd by the DAC.  This does not seem to be the case.  This needs to be addressed as soon as possible as we have told users that the DAC would provide QC.

**Comment by benjwadams** [comment]
John, do you know which dataset it was in particular?

**Comment by kerfoot** [comment]
https://data.ioos.us/gliders/erddap/tabledap/bios_minnie-20170616T1454.html

**Comment by benjwadams** [comment]
Oops, sorry, by no QC information I thought you meant it was missing QC variables entirely.  I was following that email chain but I did not initially make that association with it.

**Comment by benjwadams** [comment]
QARTOD QC on the bios* datasets has now propagated to the ERDDAP instance, so I am going to close this issue unless other issues are found down the road.

**Comment by kerfoot** [comment]
I do see that the qartod_* flags are there, but they, like the *_qc variables, do not appear to have _FillValue attributes.  Should this be filed under this issue or should I create a new issue regarding _FillValues?

**Comment by benjwadams** [comment]
I'm in the process of updating the ERDDAP template as we speak, and hope to have a fix out by this afternoon.  For *_qc variables (not sure what to informally call these), _FillValue should be nominally set to -127 for variables where it is not provided, correct?  For QARTOD QC variables in particular, the flag meanings should be the same, namely:
1 -> GOOD
2 -> UNKNOWN/NOT_EVALUATED
3 -> WARNING
4 -> BAD
9 -> MISSING

I'd argue that this would make `_FillValue` equal to 2, since the data has not been evaluated against the QC tests, and `missing_value` set to 9.  Thoughts?

**Comment by benjwadams** [comment]
Related https://github.com/ioos/ioosngdac/pull/129

**Comment by benjwadams** [comment]
We're set with this now, right?
