### ISSUE TITLE
Some deployments not including all of the `precise` location data

### ISSUE THREAD

**Issue by kwilcox** [ioos/ioosngdac#83]
Some deployments do not include `precise_lat` and `precise_lon` values for the majority of the timesteps.  I'm assuming this is because the precise location isn't actually known when the glider is underwater. Example: `sp030-20140813T1713`
![2015-09-02](https://cloud.githubusercontent.com/assets/13939/9636117/e3545e92-5167-11e5-9539-aab2e58a3ed1.png)

Some deployments do include `precise_lat` and `precise_lon` values for each time-step.  Were these interpolated? Is there an agreed upon method to backfill the deployments that did not include the interpolated positions in the DAC files? Example: `UCSC294-20150430T2218`

I see no reference to any of the `precise` variables in the documentation (https://github.com/ioos/ioosngdac/wiki/NGDAC-NetCDF-File-Format-Version-2).  Should I not use these variables and stick to using only the post-processed profile data?

**Comment by lukecampbell** [comment]
@kerfoot

**Comment by kerfoot** [comment]
There's no documentation on it since we rename the lat and lon variables in the files submitted by the user to precise_lat and precise_lon (using ERDDAP).  There is no general consensus on methods for interpolating these values from surface gps fixes.  I don't think I can give you a good answer on this, other than to use latitude and longitude, which are estimated (mean) profile positions.
